trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: croissant-api
  imageTag: $(Build.BuildId)

stages:
  - stage: Test
    jobs:
      - job: Tests
        steps:
          - script: npm test
            displayName: "Tests Node.js"

  - stage: Build_And_Push
    dependsOn: Test
    jobs:
      - job: DockerBuildPush
        steps:
          - task: Docker@2
            displayName: "Build and push vers ACR"
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: Dockerfile
              containerRegistry: sc-acr-croissant
              tags: |
                $(imageTag)
