trigger:
  - main

pr:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: "Installer Node.js"
    inputs:
      versionSpec: "20.x"

  - script: npm ci
    displayName: "Installer les dépendances"

  - script: npm test
    displayName: "Lancer les tests"
